Add more ActiveRecord operations to the rails6 test
planetscale/vitess-framework-testing pull request #85
Opened 2021-01-05 00:53 UTC by mcronce

2021-01-07 14:29 UTC, skottler requested changes

2021-01-07 14:29 UTC, skottler commented on frameworks/ruby/rails6/run.sh
> +set -o pipefail;
The semi-colons for line ending in this file aren't needed. Can you remove each of them?

2021-01-07 14:29 UTC, skottler commented on frameworks/ruby/rails6/src/lib/tasks/user.rake
> +namespace :user do
This file needs to get reformatted for consistency to 2 spaces as tabs.

2021-01-07 21:58 UTC, mcronce commented
I think we can safely say this fixes #68 and #75

2021-01-10 16:58 UTC, skottler approved these changes

2021-01-11 14:16 UTC, merged